baseURL = "https://helloworld.aworkshop.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Hello World Workshop"
theme = "learn"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
themeVariant = "mine"
showVisitedLinks = false
description = "Hello World Workshop"
disableSearch = true
disableAssetsBusting = true
disableLanguageSwitchingButton = true
disableShortcutsTitle = true

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
